# Generated by Django 5.2.4 on 2025-08-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseType', models.CharField(max_length=20)),
                ('caseNo', models.IntegerField()),
                ('caseStatus', models.CharField(max_length=20)),
                ('petitioner', models.CharField(max_length=100)),
                ('respondent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='orderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.CharField(db_index=True, max_length=10)),
                ('orderLink', models.CharField(db_index=True, max_length=100)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orders')),
            ],
        ),
    ]
