# Generated by Django 5.2.4 on 2025-08-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlink',
            name='container',
        ),
        migrations.AddField(
            model_name='orderlink',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.case'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
