# Generated by Django 5.2.4 on 2025-08-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_orderlink_container_orderlink_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=100)),
                ('filing_year', models.IntegerField()),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderlink',
            name='case',
        ),
        migrations.CreateModel(
            name='CourtResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.TextField()),
                ('response_timestamp', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.IntegerField()),
                ('is_success', models.BooleanField(default=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.courtquery')),
            ],
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='orderLink',
        ),
    ]
